Fix lightning import issue due to protobuf
Summary:
It fails at importing pytorch_lightning. This issue is caused by protobuf and fixed in lightning by pinning "protobuf<=3.20.1": https://github.com/PyTorchLightning/pytorch-lightning/issues/13159

Reproduce:
  (recipes) ➜ python dlrm_main.py
  Traceback (most recent call last):
  File "dlrm_main.py", line 14, in <module>
    import pytorch_lightning as pl
  File "/Users/stevenliu/opt/anaconda3/envs/recipes/lib/python3.7/site-packages/pytorch_lightning/__init__.py", line 30, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/Users/stevenliu/opt/anaconda3/envs/recipes/lib/python3.7/site-packages/pytorch_lightning/callbacks/__init__.py", line 26, in <module>
    from pytorch_lightning.callbacks.pruning import ModelPruning
  File "/Users/stevenliu/opt/anaconda3/envs/recipes/lib/python3.7/site-packages/pytorch_lightning/callbacks/pruning.py", line 31, in <module>
    from pytorch_lightning.core.lightning import LightningModule
  File "/Users/stevenliu/opt/anaconda3/envs/recipes/lib/python3.7/site-packages/pytorch_lightning/core/__init__.py", line 16, in <module>
    from pytorch_lightning.core.lightning import LightningModule
  File "/Users/stevenliu/opt/anaconda3/envs/recipes/lib/python3.7/site-packages/pytorch_lightning/core/lightning.py", line 40, in <module>
    from pytorch_lightning.loggers import LightningLoggerBase
  File "/Users/stevenliu/opt/anaconda3/envs/recipes/lib/python3.7/site-packages/pytorch_lightning/loggers/__init__.py", line 18, in <module>
    from pytorch_lightning.loggers.tensorboard import TensorBoardLogger
  File "/Users/stevenliu/opt/anaconda3/envs/recipes/lib/python3.7/site-packages/pytorch_lightning/loggers/tensorboard.py", line 26, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/Users/stevenliu/opt/anaconda3/envs/recipes/lib/python3.7/site-packages/torch/utils/tensorboard/__init__.py", line 10, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "/Users/stevenliu/opt/anaconda3/envs/recipes/lib/python3.7/site-packages/torch/utils/tensorboard/writer.py", line 9, in <module>
    from tensorboard.compat.proto.event_pb2 import SessionLog
  File "/Users/stevenliu/opt/anaconda3/envs/recipes/lib/python3.7/site-packages/tensorboard/compat/proto/event_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import summary_pb2 as tensorboard_dot_compat_dot_proto_dot_summary__pb2
  File "/Users/stevenliu/opt/anaconda3/envs/recipes/lib/python3.7/site-packages/tensorboard/compat/proto/summary_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import tensor_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__pb2
  File "/Users/stevenliu/opt/anaconda3/envs/recipes/lib/python3.7/site-packages/tensorboard/compat/proto/tensor_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import resource_handle_pb2 as tensorboard_dot_compat_dot_proto_dot_resource__handle__pb2
  File "/Users/stevenliu/opt/anaconda3/envs/recipes/lib/python3.7/site-packages/tensorboard/compat/proto/resource_handle_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import tensor_shape_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__shape__pb2
  File "/Users/stevenliu/opt/anaconda3/envs/recipes/lib/python3.7/site-packages/tensorboard/compat/proto/tensor_shape_pb2.py", line 42, in <module>
    serialized_options=None, file=DESCRIPTOR),
  File "/Users/stevenliu/opt/anaconda3/envs/recipes/lib/python3.7/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
  TypeError: Descriptors cannot not be created directly.
  If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
  If you cannot immediately regenerate your protos, some other possible workarounds are:
   1. Downgrade the protobuf package to 3.20.x or lower.
   2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

  More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

Reviewed By: colin2328

Differential Revision: D36875536

fbshipit-source-id: 0233696282b1f49dd0e061024e6ddb965df1d8df